-- MySQL Script generated by MySQL Workbench
-- Sun Apr  5 02:17:40 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sendapoem
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sendapoem
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sendapoem` DEFAULT CHARACTER SET utf8 ;
USE `sendapoem` ;

-- -----------------------------------------------------
-- Table `sendapoem`.`author`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sendapoem`.`author` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(120) NOT NULL,
  `email` VARCHAR(120) NOT NULL,
  `phone` VARCHAR(20) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `picture` VARCHAR(120) NULL,
  `create_at` TIMESTAMP NOT NULL DEFAULT NOW(),
  `status` TINYINT NOT NULL DEFAULT 4,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `phone_UNIQUE` (`phone` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sendapoem`.`poem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sendapoem`.`poem` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_author` INT NOT NULL,
  `title` VARCHAR(120) NOT NULL,
  `body` LONGTEXT NOT NULL,
  `create_at` TIMESTAMP NOT NULL DEFAULT NOW(),
  PRIMARY KEY (`id`),
  INDEX `fk_poem_user_idx` (`id_author` ASC) VISIBLE,
  CONSTRAINT `fk_poem_user`
    FOREIGN KEY (`id_author`)
    REFERENCES `sendapoem`.`author` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sendapoem`.`follower`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sendapoem`.`follower` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_author_following` INT NOT NULL,
  `id_author_followed` INT NOT NULL,
  `create_at` TIMESTAMP NOT NULL DEFAULT NOW(),
  PRIMARY KEY (`id`),
  INDEX `fk_follower_author1_idx` (`id_author_following` ASC) VISIBLE,
  INDEX `fk_follower_author2_idx` (`id_author_followed` ASC) VISIBLE,
  CONSTRAINT `fk_follower_author1`
    FOREIGN KEY (`id_author_following`)
    REFERENCES `sendapoem`.`author` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_follower_author2`
    FOREIGN KEY (`id_author_followed`)
    REFERENCES `sendapoem`.`author` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sendapoem`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sendapoem`.`comment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_poem` INT NOT NULL,
  `id_author` INT NOT NULL,
  `message` VARCHAR(225) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_comments_author1_idx` (`id_author` ASC) VISIBLE,
  INDEX `fk_comments_poem1_idx` (`id_poem` ASC) VISIBLE,
  CONSTRAINT `fk_comments_author1`
    FOREIGN KEY (`id_author`)
    REFERENCES `sendapoem`.`author` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comments_poem1`
    FOREIGN KEY (`id_poem`)
    REFERENCES `sendapoem`.`poem` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sendapoem`.`code`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sendapoem`.`code` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_author` INT NOT NULL,
  `value` VARCHAR(6) NOT NULL,
  `expires` TIMESTAMP NOT NULL,
  INDEX `fk_table1_author1_idx` (`id_author` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_table1_author1`
    FOREIGN KEY (`id_author`)
    REFERENCES `sendapoem`.`author` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
